### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by lcebaman** [mila-iqia/milabench#192]
How can we solve the CUDA out of memory problem running opt-6_7b ?

`torch.cuda.OutOfMemoryError: Cuda out of memory`

Each GPU has 40GB of memory, what is the memory requirement for this tests?

**Comment by Delaunay** [comment]
That benchmark takes 78850 Mo of memory. Its batch size is one.
There is nothing that can be done to reduce its memory footprint.

**Comment by lcebaman** [comment]
Is this also the memory requirement for the multinode case? 78850 Mo of memory per GPU?

**Comment by Delaunay** [comment]
The memory requirement will depend on the specific setup, it is hard to generalize.
You can find examples of what I observed but that might not be hold true for your hardware.

* One Node:
    * 1 x 4 GPU: 78'000 Mo
    * 1 x 8 GPU: 53'000 Mo
* Two Node:
    * 2 x 8 GPU: 49'000 Mo
