### ISSUE TITLE
MILABENCH_GPU_ARCH undocumented

### ISSUE THREAD

**Issue by gravitino** [mila-iqia/milabench#39]
milabench install for standard-coda crashes when aforementioned env variable is not set.

**Comment by breuleux** [comment]
Normally it shouldn't be necessary to set it unless you have both NVIDIA and AMD GPUs on the machine (or if the parsing of nvidia-smi fails, apparently) but I'll document it.

**Comment by breuleux** [comment]
I added a mention of this in https://mila-iqia.github.io/milabench/usage.html, which should do for now.
