### ISSUE TITLE
use https instead of git uris

### ISSUE THREAD

**Issue by tbugfinder** [mila-iqia/milabench#4]
Hi,

builds running in firewalled networks might fail. Would it be possible to convert to https URIs?

Thanks.

**Comment by lcebaman** [comment]
Is there any progress on this?

**Comment by Delaunay** [comment]
Will the pre-built docker images solve this issue ?
They contain all the data for the bench to run right away, no additional downloads are necessary.

**Comment by tbugfinder** [comment]
I'll give the container a try, too :-D thx!

**Comment by Delaunay** [comment]
Ok, all those links are gone now.
I am going to mark it as resolved then.
