### ISSUE TITLE
Problem installing milabench

### ISSUE THREAD

**Issue by guylaporte** [mila-iqia/milabench#41]
When installing milabench it fails at this level:

Collecting tornado
  Using cached tornado-6.2-cp37-abi3-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (423 kB)
Collecting pyasn1<0.5.0,>=0.4.6
  Using cached pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
Collecting oauthlib>=3.0.0
  Using cached oauthlib-3.2.2-py3-none-any.whl (151 kB)
Building wheels for collected packages: AutoROM.accept-rom-license
  Building wheel for AutoROM.accept-rom-license (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for AutoROM.accept-rom-license (pyproject.toml) did not run successfully.

It looks like the reason is a failure to download the atari roms.

I am attaching a file with the complete install logs.
[install_logs_01242023.txt](https://github.com/mila-iqia/milabench/files/10494300/install_logs_01242023.txt)

**Comment by breuleux** [comment]
Does `pip install -vvv AutoROM.accept-rom-license` succeed if you run it by itself? It did for me (version 0.5.4, same as the one I see in the install logs, although on Python 3.10).

**Comment by guylaporte** [comment]
I am getting the same error.  I will try installing python3.10.

**Comment by guylaporte** [comment]
I ran some packet captures and it seems that something is blocked in the firewall.  I will move to a different environment.

**Comment by guylaporte** [comment]
I confirmed that the firewall is blocking the download of atari roms.  Please let me know if you can think of a workaround.  If not, this ticket can be closed.  Thank you.

**Comment by breuleux** [comment]
AFAIK the `ppo` benchmark requires the roms (maybe `sb3` too), but you can exclude it with `--exclude ppo`, which should at least allow you to test the rest. You can use a comma-separated list if you want to exclude multiple tests.
