### ISSUE TITLE
Error running milabench with H100 GPU

### ISSUE THREAD

**Issue by guylaporte** [mila-iqia/milabench#44]
```
resnet50.D0 >! /home/mila/milabench/venv/torchvision/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py:262: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
  warnings.warn(
resnet50.D0 >! /home/mila/milabench/venv/torchvision/lib/python3.8/site-packages/torch/cuda/__init__.py:155: UserWarning:
NVIDIA H100 PCIe with CUDA capability sm_90 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70 sm_75 sm_80 sm_86.
If you want to use the NVIDIA H100 PCIe GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/
 
  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
```

I am running pytorch 1.13.1.

**Comment by btravouillon** [comment]
Hello,

H100 GPUs require CUDA 12 and capabilities `sm_90`.

Looks like support of CUDA 12 in Pytorch is not ready yet. https://github.com/pytorch/pytorch/issues/91122

**Comment by btravouillon** [comment]
@breuleux : is pytorch required to run all milabench tests? Or is it possible to disable some tests?

**Comment by btravouillon** [comment]
@guylaporte this may work with CUDA 11.8 and a Pytorch preview (nightly) build.

**Comment by guylaporte** [comment]
Tried CUDA 11.8 and Pytorch 2.0.0 (nightly) and I get the same error:

resnet50.D0 >! /home/mila/milabench/venv/torchvision/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py:262: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
  warnings.warn(
resnet50.D0 >! /home/mila/milabench/venv/torchvision/lib/python3.8/site-packages/torch/cuda/__init__.py:155: UserWarning:
NVIDIA H100 PCIe with CUDA capability sm_90 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70 sm_75 sm_80 sm_86.
If you want to use the NVIDIA H100 PCIe GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
^Cresnet50.D0 {'#end': 1674833583.2164211, '#completed': False, '#error': 'KeyboardInterrupt: '}
[DONE] Reports directory: /home/mila/milabench/runs/sejufuvo.2023-01-27_15:25:40.821874

(base) mila@csctmp-r7525-6:~/milabench$ conda list |grep torch
pytorch                   2.0.0.dev20230127 py3.9_cuda11.8_cudnn8.7.0_0    pytorch-nightly
pytorch-cuda              11.8                 h8dd9ede_2    pytorch-nightly
pytorch-mutex             1.0                        cuda    pytorch-nightly
torchaudio                2.0.0.dev20230127      py39_cu118    pytorch-nightly
torchtriton               2.0.0+0d7e753227            py39    pytorch-nightly
torchvision               0.15.0.dev20230127      py39_cu118    pytorch-nightly

(base) mila@csctmp-r7525-6:~/milabench$ pip3 list |grep torch
pytorch-triton           2.0.0+0d7e753227
torch                    2.0.0.dev20230127+cu118
torchaudio               2.0.0.dev20230127+cu118
torchvision              0.15.0.dev20230127+cu118

(base) mila@csctmp-r7525-6:~/milabench$ nvidia-smi
Fri Jan 27 15:33:38 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 520.61.05    Driver Version: 520.61.05    CUDA Version: 11.8     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA H100 PCIe    Off  | 00000000:21:00.0 Off |                    0 |
| N/A   34C    P0    66W / 310W |      0MiB / 81559MiB |     10%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

**Comment by breuleux** [comment]
Milabench runs the benchmarks in their own virtual environments, not the one you see with conda list in the milabench directory. As a check, try `milabench run --select resnet50 --use-current-env`.

If that works, try adding this code [around here](https://github.com/mila-iqia/milabench/blob/master/config/standard-cuda.yaml#L10)

```yaml
  pip:
    args:
      - --pre
      - --index-url
      - https://download.pytorch.org/whl/nightly/cu118
```

Then reinstall with `milabench install --force` and it should hopefully then use the nightly Pytorch build.

**Comment by guylaporte** [comment]
This test (milabench run --select resnet50 --use-current-env) worked fine.  When I try to install with the addition to the standard-cuda.yaml file, I get this error:

(base) mila@csctmp-r7525-6:~/milabench$ milabench install --force
resnet50 > Clearing existing data in /home/mila/milabench/code/torchvision
Looking in indexes: https://download.pytorch.org/whl/nightly/cu118
Requirement already satisfied: pip in ./venv/torchvision/lib/python3.8/site-packages (22.3.1)
Looking in indexes: https://download.pytorch.org/whl/nightly/cu118
Obtaining file:///home/mila/milabench
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      Looking in indexes: https://download.pytorch.org/whl/nightly/cu118
      ERROR: Could not find a version that satisfies the requirement poetry-core>=1.0.0 (from versions: none)
      ERROR: No matching distribution found for poetry-core>=1.0.0
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
resnet50 >! Command python -m pip install -e /home/mila/milabench --pre --index-url https://download.pytorch.org/whl/nightly/cu118 failed with exit code 1
Traceback (most recent call last):
  File "/home/mila/.local/bin/milabench", line 8, in <module>
    sys.exit(main())
  File "/home/mila/milabench/milabench/cli.py", line 23, in main
    run_cli(Main)
  File "/home/mila/.local/lib/python3.8/site-packages/coleo/cli.py", line 628, in run_cli
    return call(opts=opts, args=args)
  File "/home/mila/.local/lib/python3.8/site-packages/coleo/cli.py", line 587, in thunk
    result = fn(*args)
  File "/home/mila/milabench/milabench/cli.py", line 223, in install
    mp.do_install(dash=simple_dash, force=force, sync=sync)
  File "/home/mila/milabench/milabench/multi.py", line 92, in do_install
    pack.checked_install(force=force, sync=sync)
  File "/home/mila/milabench/milabench/pack.py", line 104, in checked_install
    self.install_milabench()
  File "/home/mila/milabench/milabench/pack.py", line 151, in install_milabench
    self.pip_install("-e", mb_parent)
  File "/home/mila/milabench/milabench/pack.py", line 167, in pip_install
    return self._nox_session.install(*args, **kwargs, silent=False)
  File "/home/mila/.local/lib/python3.8/site-packages/nox/sessions.py", line 476, in install
    self._run("python", "-m", "pip", "install", *args, external="error", **kwargs)
  File "/home/mila/.local/lib/python3.8/site-packages/nox/sessions.py", line 360, in _run
    return nox.command.run(args, env=env, paths=self.bin_paths, **kwargs)
  File "/home/mila/.local/lib/python3.8/site-packages/nox/command.py", line 126, in run
    raise CommandFailed(f"Returned code {return_code}")
nox.command.CommandFailed: Returned code 1

I installed poetry-core but it did not help.

**Comment by breuleux** [comment]
Oh yes, it should be `--extra-index-url` instead of `--index-url`, sorry.

**Comment by guylaporte** [comment]
The installation completed without errors.  I gather that I have to use "--use-current-env" when I run the benchmark?  If not, I get the original error.

**Comment by breuleux** [comment]
`--use-current-env` should not be required after that install, so that's a bit odd. What's the log of the install command?

**Comment by guylaporte** [comment]
Here are the install logs.
[install_logs_01272023.txt](https://github.com/mila-iqia/milabench/files/10521477/install_logs_01272023.txt)

**Comment by breuleux** [comment]
I see, I think `milabench install --force` isn't smart enough, it doesn't install the nightly because it considers that torch is already installed. Wipe out `$MILABENCH_BASE/venv` and try the command again.

**Comment by guylaporte** [comment]
The installation succeeded and I was able to start the run without the --use-current-env.  Many tests succeeded but one failed with the same error as before:

resnet152.0 >! /home/mila/milabench/venv/lightning/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py:446: LightningDeprecationWarning: Setting `Trainer(gpus=-1)` is deprecated in v1.7 and will be removed in v2.0. Please use `Trainer(accelerator='gpu', devices=-1)` instead.
  rank_zero_deprecation(
resnet152.0 >! /home/mila/milabench/venv/lightning/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py:466: UserWarning: The flag `devices=-1` will be ignored, instead the device specific number -1 will be used
  rank_zero_warn(
resnet152.0 >! GPU available: True (cuda), used: True
resnet152.0 >! TPU available: False, using: 0 TPU cores
resnet152.0 >! IPU available: False, using: 0 IPUs
resnet152.0 >! HPU available: False, using: 0 HPUs
resnet152.0 > Model Hyper-Parameters: "hp": {'backbone': 'resnet152', 'lr': 0.0003, 'batch_size': 2048}
resnet152.0 >! /home/mila/milabench/venv/lightning/lib/python3.8/site-packages/torch/cuda/__init__.py:155: UserWarning:
NVIDIA H100 PCIe with CUDA capability sm_90 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70 sm_75 sm_80 sm_86.
If you want to use the NVIDIA H100 PCIe GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
resnet152.0 > Files already downloaded and verified
resnet152.0 > Files already downloaded and verified
resnet152.0 >! Missing logger folder: /home/mila/milabench/code/lightning/lightning_logs
resnet152.0 >! LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Could there be one location that still points to the original torch version?

**Comment by breuleux** [comment]
The error occurs inside `/home/mila/milabench/venv/lightning` which is inside the directory I told you to wipe, so I don't think it's a leftover.

This is likely because the versions for this one are pinned (https://github.com/mila-iqia/milabench/blob/master/benchmarks/pytorch-lightning/frozen_reqs.cuda.txt#L225). You can try to update that file and reinstall. However, it *may* still not work since `pytorch-lightning` appears to specify an upper bound on its own pytorch dependency, which would cause pip's resolver to fail or fall back to a previous version (https://github.com/Lightning-AI/lightning/blob/master/requirements/pytorch/base.txt#L5, which is not in milabench).

If all else fails, probably the quickest solve is to run `/home/mila/milabench/venv/lightning/bin/activate` in a new shell to activate that specific environment and install the working version of Pytorch in there yourself. If the test still fails, that benchmark may just be incompatible with the H100 for the time being.

**Comment by guylaporte** [comment]
Updating the version in the file caused installation errors due to dependencies:

ERROR: Cannot install -r /home/mila/milabench/code/lightning/frozen_reqs.cuda.txt (line 103), -r /home/mila/milabench/code/lightning/frozen_reqs.cuda.txt (line 174), -r /home/mila/milabench/code/lightning/frozen_reqs.cuda.txt (line 232), -r /home/mila/milabench/code/lightning/frozen_reqs.cuda.txt (line 61), torch==2.0.0.dev20230127+cu118 and torchvision==0.14.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested torch==2.0.0.dev20230127+cu118
    fairscale 0.4.12 depends on torch>=1.8.0
    lightning 1.8.3.post1 depends on torch>=1.9.*
    pytorch-lightning 1.8.3.post1 depends on torch>=1.9.*
    torchmetrics 0.10.3 depends on torch>=1.3.1
    torchvision 0.14.0 depends on torch==1.13.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
resnet152 >! Command python -m pip install -r /home/mila/milabench/code/lightning/frozen_reqs.cuda.txt --pre --extra-index-url https://download.pytorch.org/whl/nightly/cu118 failed with exit code 1
Traceback (most recent call last):
  File "/home/mila/.local/bin/milabench", line 8, in <module>
    sys.exit(main())
  File "/home/mila/milabench/milabench/cli.py", line 23, in main
    run_cli(Main)
  File "/home/mila/.local/lib/python3.8/site-packages/coleo/cli.py", line 628, in run_cli
    return call(opts=opts, args=args)
  File "/home/mila/.local/lib/python3.8/site-packages/coleo/cli.py", line 587, in thunk
    result = fn(*args)
  File "/home/mila/milabench/milabench/cli.py", line 223, in install
    mp.do_install(dash=simple_dash, force=force, sync=sync)
  File "/home/mila/milabench/milabench/multi.py", line 92, in do_install
    pack.checked_install(force=force, sync=sync)
  File "/home/mila/milabench/milabench/pack.py", line 105, in checked_install
    self.install()
  File "/home/mila/milabench/milabench/pack.py", line 307, in install
    self.pip_install("-r", reqs)
  File "/home/mila/milabench/milabench/pack.py", line 167, in pip_install
    return self._nox_session.install(*args, **kwargs, silent=False)
  File "/home/mila/.local/lib/python3.8/site-packages/nox/sessions.py", line 476, in install
    self._run("python", "-m", "pip", "install", *args, external="error", **kwargs)
  File "/home/mila/.local/lib/python3.8/site-packages/nox/sessions.py", line 360, in _run
    return nox.command.run(args, env=env, paths=self.bin_paths, **kwargs)
  File "/home/mila/.local/lib/python3.8/site-packages/nox/command.py", line 126, in run
    raise CommandFailed(f"Returned code {return_code}")
nox.command.CommandFailed: Returned code 1


I will try with a new veenv.

**Comment by guylaporte** [comment]
I tried "the quickest solve is to run /home/mila/milabench/venv/lightning/bin/activate in a new shell to activate that specific environment and install the working version of Pytorch in there yourself." and did not have much success.  I am probably not understanding this correctly.  Are there more steps I could follow?

**Comment by breuleux** [comment]
I forgot the file has to be `source`d and not executed, I mean something like this:

```bash
source /home/mila/milabench/venv/lightning/bin/activate
pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu118
deactivate
```

**Comment by guylaporte** [comment]
I figured the you meant activate and this is what I did.  I did not think about deactivating before running the installation again so I tried it.  Unfortunately, I am getting the same error:

ERROR: Cannot install -r /home/mila/milabench/code/lightning/frozen_reqs.cuda.txt (line 103), -r /home/mila/milabench/code/lightning/frozen_reqs.cuda.txt (line 174), -r /home/mila/milabench/code/lightning/frozen_reqs.cuda.txt (line 232), -r /home/mila/milabench/code/lightning/frozen_reqs.cuda.txt (line 236), -r /home/mila/milabench/code/lightning/frozen_reqs.cuda.txt (line 61) and torch==2.0.0.dev20230127+cu118 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested torch==2.0.0.dev20230127+cu118
    fairscale 0.4.12 depends on torch>=1.8.0
    lightning 1.8.3.post1 depends on torch>=1.9.*
    pytorch-lightning 1.8.3.post1 depends on torch>=1.9.*
    torchmetrics 0.10.3 depends on torch>=1.3.1
    torchvision 0.14.0 depends on torch==1.13.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
resnet152 >! Command python -m pip install -r /home/mila/milabench/code/lightning/frozen_reqs.cuda.txt --pre --extra-index-url https://download.pytorch.org/whl/nightly/cu118 failed with exit code 1
Traceback (most recent call last):
  File "/home/mila/.local/bin/milabench", line 8, in <module>
    sys.exit(main())
  File "/home/mila/milabench/milabench/cli.py", line 23, in main
    run_cli(Main)
  File "/home/mila/.local/lib/python3.8/site-packages/coleo/cli.py", line 628, in run_cli
    return call(opts=opts, args=args)
  File "/home/mila/.local/lib/python3.8/site-packages/coleo/cli.py", line 587, in thunk
    result = fn(*args)
  File "/home/mila/milabench/milabench/cli.py", line 223, in install
    mp.do_install(dash=simple_dash, force=force, sync=sync)
  File "/home/mila/milabench/milabench/multi.py", line 92, in do_install
    pack.checked_install(force=force, sync=sync)
  File "/home/mila/milabench/milabench/pack.py", line 105, in checked_install
    self.install()
  File "/home/mila/milabench/milabench/pack.py", line 307, in install
    self.pip_install("-r", reqs)
  File "/home/mila/milabench/milabench/pack.py", line 167, in pip_install
    return self._nox_session.install(*args, **kwargs, silent=False)
  File "/home/mila/.local/lib/python3.8/site-packages/nox/sessions.py", line 476, in install
    self._run("python", "-m", "pip", "install", *args, external="error", **kwargs)
  File "/home/mila/.local/lib/python3.8/site-packages/nox/sessions.py", line 360, in _run
    return nox.command.run(args, env=env, paths=self.bin_paths, **kwargs)
  File "/home/mila/.local/lib/python3.8/site-packages/nox/command.py", line 126, in run
    raise CommandFailed(f"Returned code {return_code}")
nox.command.CommandFailed: Returned code 1

**Comment by Delaunay** [comment]
I am closing this as resolved.
We were able to run the docker image of milabench on H100.
I opened another ticket for the last remaining bench that is not working and another one for the firewall issue.

* https://github.com/mila-iqia/milabench/issues/70
* https://github.com/mila-iqia/milabench/issues/69
