### ISSUE TITLE
move anaconda installation

### ISSUE THREAD

**Issue by tbugfinder** [mila-iqia/milabench#5]
Hi,

I've built the image and executed it using singularity.
Unfortunately as a normal user I cannot cd into /root and list the anaconda installation.
Would it be an option to move anaconda also to /workspace? Is there a specific reason using /root?

Thanks 

https://github.com/mila-iqia/milabench/blob/5349c6b8b58261149799d52b742720ad6224208c/Dockerfile#L22

**Comment by tbugfinder** [comment]
I've adopted Dockerfile for my usecase successfully.
However I understand that there are reasons to use docker and root.

In my case it would be most preferred if the simulation of multiple users would be indeed based on distinct Slurm jobs backed by singularity containers.

**Comment by Delaunay** [comment]
Can you open a separate issue about the multiple user simulation ?
we had in the past did something similar through cgroups (which is what slurm does).

In the meantime, I will close; this the newest dockerfile has a [`CONDA_PATH`](https://github.com/mila-iqia/milabench/blob/master/Dockerfile#L52) environment that you can tweak to change the anaconda install location.
It defaults to `/opt/anaconda`
